In [1]:
import numpy as np

In [10]:
#Array functions
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr + 5
arr - 2
arr * 6
arr + arr #As long as they're the same shape
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [9]:
np.sqrt(arr)
#np.log(arr) - returns warning as a 0 divisional error
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [11]:
arr.sum()
arr.mean()
arr.var()
arr.std()

2.8722813232690143

In [12]:
#2D Array Functions

In [16]:
arr_2d = np.arange(0,25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
arr_2d.shape

(5, 5)

In [19]:
arr_2d.sum(axis=0) #Sum of all the columns (Across the rows)

array([50, 55, 60, 65, 70])

In [20]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])