In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr[1:5] #Indexing - single colon selects entire array '[:]'

array([1, 2, 3, 4])

In [6]:
arr[:4]

array([0, 1, 2, 3])

In [8]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [11]:
#Broadcasting array reassignment

In [13]:
arr[0:5] = 50
arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10])

In [14]:
#Reset
arr = np.arange(0,11)

In [16]:
#Slicing
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [21]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
#Effects the original array, to avoid create a copy
arr_copy = arr.copy()
arr_copy[:5] = 20
arr_copy

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9, 10])

In [26]:
#Indexing on a 2D array - Dimension for rows and columns

In [25]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d.shape

(3, 3)

In [30]:
arr_2d[1,2] #Row then column position

30

In [31]:
#Slice sections of the matrix

In [32]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [33]:
#Conditional Selection

In [35]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
bool_arr = arr > 3
bool_arr

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [39]:
arr[bool_arr] #Use boolean array to filter out original array

array([ 4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[arr>4]
#simplified version

array([ 5,  6,  7,  8,  9, 10])