In [1]:
import numpy as np

In [3]:
#Create NumPy Array

In [4]:
my_list = [1,2,3]

In [5]:
type(my_list)

list

In [6]:
np.array(my_list)

array([1, 2, 3])

In [12]:
#Still just a list, convert to np array

In [10]:
np_array = np.array(my_list)

In [11]:
np_array

array([1, 2, 3])

In [13]:
type(np_array)

numpy.ndarray

In [14]:
#NumPy recognises nested lists as 2D

In [16]:
np.arange(0,10,2) #0 through 9, with a step size of 2

array([0, 2, 4, 6, 8])

In [20]:
np.ones((2,5)) #Creates 2D array denoting rows and columns, same for 'zeros'

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.linspace(0,10,21) #Returns evenly spaced numbers over a specified interval - 0 through 10 with 20 intervals

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [26]:
np.eye(5) #Creates an identity matrix - Same number of rows and columns

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(5) #Returns a random array between 0 and 1 - 0 is inclusive, 1 is exclusive

array([0.34949584, 0.88336038, 0.5352897 , 0.86010567, 0.78829931])

In [30]:
np.random.rand(2, 3) #Can also pass in a shape with 2 parameters, rows x columns

array([[0.21545213, 0.13808891, 0.12382092],
       [0.03762241, 0.23617432, 0.83446996]])

In [38]:
np.random.randn(2, 3) #Creates samples from a standard distribution - Mean is 0 - Numbers closer to 0 have a higher likelyhood of being selected

array([[ 1.00016585, -0.30773613, -0.57174056],
       [-0.70135479, -0.35895223, -0.84290938]])

In [39]:
np.random.randint(1, 101, (2,3)) #Return and array 1 inclusive, 101 exclusive in a 2 x 3 array

array([[59, 92, 29],
       [74, 15, 85]])

In [45]:
np.random.seed(42) #Seed will select a particular set of random numbers - They will always be the same - Important for testing random distribution models
np.random.rand(7)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361])

In [54]:
#Reshape Arrays - Must fit the same number of elements

In [51]:
arr = np.arange(0,25)

In [53]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
ranarr = np.random.randint(0,101,10)
ranarr

array([87, 99, 23,  2, 21, 52,  1, 87, 29, 37])

In [61]:
ranarr.max() # Checks for max/min/mean value in array
ranarr.min()
ranarr.mean()

43.8

In [64]:
ranarr.argmin() #Checks for index of min number of array

6

In [65]:
ranarr.dtype #Checks data type of array

dtype('int32')

In [67]:
ranarr.shape #Checks shape of array

(10,)